name: All_branchs_commit_convention
on: 
  push:
    branches:
      - 'feature/**'
      - 'hotfix/**'

jobs:
  if_commit_convention:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: webiny/action-coventional-commits@v1.0.5
      


